# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_base', models.DecimalField(decimal_places=2, help_text='Prix selon le mode de tarification du service', max_digits=10, verbose_name='Prix de base (FCFA)')),
                ('delai', models.PositiveIntegerField(help_text='Temps de réalisation promis par le prestataire', verbose_name='Délai (heures)')),
                ('is_available', models.BooleanField(default=True, help_text='Le prestataire propose actuellement ce service', verbose_name='Disponible')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider', verbose_name='Prestataire')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service du prestataire',
                'verbose_name_plural': 'Services des prestataires',
                'ordering': ['provider', 'service'],
                'unique_together': {('provider', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='services.articletype', verbose_name="Type d'article")),
                ('matiere', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer à toutes les matières', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='services.matiere', verbose_name='Matière')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='providers.provider', verbose_name='Prestataire')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Tarif personnalisé',
                'verbose_name_plural': 'Tarifs personnalisés',
                'ordering': ['provider', 'article_type', 'service'],
                'unique_together': {('provider', 'article_type', 'matiere', 'service')},
            },
        ),
    ]
