# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'article")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Template de type d'article",
                'verbose_name_plural': "Templates de types d'articles",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MatiereTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Template de matière',
                'verbose_name_plural': 'Templates de matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Libellé du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mode_tarif', models.CharField(choices=[('kg', 'Au kilogramme'), ('piece', 'Par pièce'), ('forfait', 'Forfait')], max_length=20, verbose_name='Mode de tarification')),
                ('duree_estimee', models.PositiveIntegerField(help_text='Temps moyen de réalisation', verbose_name='Durée estimée (minutes)')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: iron, washing-machine)", max_length=50, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Template de service',
                'verbose_name_plural': 'Templates de services',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_types', to='providers.provider', verbose_name='Prestataire')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='services.articletypetemplate', verbose_name='Basé sur le template')),
            ],
            options={
                'verbose_name': "Type d'article",
                'verbose_name_plural': "Types d'articles",
                'ordering': ['provider', 'nom'],
                'indexes': [models.Index(fields=['provider'], name='services_ar_provide_cf15a3_idx')],
                'unique_together': {('provider', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='providers.provider', verbose_name='Prestataire')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='services.matieretemplate', verbose_name='Basé sur le template')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['provider', 'nom'],
                'indexes': [models.Index(fields=['provider'], name='services_ma_provide_823ed3_idx')],
                'unique_together': {('provider', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, verbose_name='Libellé du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mode_tarif', models.CharField(choices=[('kg', 'Au kilogramme'), ('piece', 'Par pièce'), ('forfait', 'Forfait')], max_length=20, verbose_name='Mode de tarification')),
                ('duree_estimee', models.PositiveIntegerField(help_text='Temps moyen de réalisation', verbose_name='Durée estimée (minutes)')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: iron, washing-machine)", max_length=50, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider', verbose_name='Prestataire')),
                ('template', models.ForeignKey(blank=True, help_text='Template utilisé comme base (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='services.servicetemplate', verbose_name='Basé sur le template')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['provider', 'label'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='services_se_provide_679d85_idx')],
                'unique_together': {('provider', 'label')},
            },
        ),
    ]
