# Generated by Django 5.2.7 on 2025-10-10 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'article")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Type d'article",
                'verbose_name_plural': "Types d'articles",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Libellé du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mode_tarif', models.CharField(choices=[('kg', 'Au kilogramme'), ('piece', 'Par pièce'), ('forfait', 'Forfait')], max_length=20, verbose_name='Mode de tarification')),
                ('duree_estimee', models.PositiveIntegerField(help_text='Temps moyen de réalisation', verbose_name='Durée estimée (minutes)')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: iron, washing-machine)", max_length=50, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['label'],
            },
        ),
    ]
