# Generated by Django 5.2.7 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerstaff_unique_together_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indique si le service a été supprimé (soft delete)', verbose_name='Supprimé'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('provider', 'label'), name='unique_service_label_per_provider_active'),
        ),
    ]
