# Generated by Django 5.2.7 on 2025-10-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de vérification du numéro de téléphone', null=True, verbose_name='Téléphone vérifié le'),
        ),
    ]
