# Generated by Django 5.2.7 on 2026-01-25 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFCMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token unique généré par Firebase pour ce device', max_length=500, unique=True, verbose_name='Token FCM')),
                ('device_type', models.CharField(choices=[('web', 'Navigateur Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20, verbose_name='Type de device')),
                ('device_name', models.CharField(blank=True, help_text='Ex: Chrome sur Windows, iPhone 15, Samsung Galaxy S24', max_length=200, verbose_name='Nom du device')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='User-Agent, OS, version navigateur, etc.', verbose_name='Informations device')),
                ('is_active', models.BooleanField(default=True, help_text='False si le token est invalide ou révoqué', verbose_name='Actif')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Dernière notification envoyée avec succès', null=True, verbose_name='Dernière utilisation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token FCM',
                'verbose_name_plural': 'Tokens FCM',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_userf_user_id_8ca682_idx'), models.Index(fields=['token'], name='users_userf_token_a7e5bf_idx'), models.Index(fields=['device_type'], name='users_userf_device__fd3e2e_idx')],
            },
        ),
    ]
