# Generated by Django 5.2.7 on 2026-01-25 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_enabled', models.BooleanField(default=True, help_text="Notifications sur l'appareil", verbose_name='Notifications push')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('sms_enabled', models.BooleanField(default=False, help_text='SMS pour événements critiques uniquement', verbose_name='Notifications SMS')),
                ('notify_order_confirmations', models.BooleanField(default=True, help_text='Quand une commande est passée', verbose_name='Confirmations de commande')),
                ('notify_order_updates', models.BooleanField(default=True, help_text='Changements de statut', verbose_name='Mises à jour commandes')),
                ('notify_delivery', models.BooleanField(default=True, help_text='Notifications de livraison et OTP', verbose_name='Livraisons')),
                ('notify_payments', models.BooleanField(default=True, help_text='Confirmations de paiement', verbose_name='Paiements')),
                ('notify_promotions', models.BooleanField(default=False, help_text='Offres et promotions (optionnel)', verbose_name='Promotions')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
    ]
