# Generated by Django 5.2.7 on 2025-10-15 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(help_text='Nom affiché dans le dashboard', max_length=200, verbose_name='Nom commercial affiché')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/logos/%Y/%m/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Format hex: #RRGGBB', max_length=7, verbose_name='Couleur principale')),
                ('auto_accept_orders', models.BooleanField(default=False, verbose_name='Acceptation automatique des commandes')),
                ('require_payment_before', models.BooleanField(default=False, verbose_name='Exiger le paiement avant traitement')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant minimum de commande (FCFA)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison par défaut (FCFA)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de notification')),
                ('notification_phone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone de notification')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Format JSON avec les horaires par jour', verbose_name="Horaires d'ouverture")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Paramètres supplémentaires en JSON', verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètres du prestataire',
                'verbose_name_plural': 'Paramètres des prestataires',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Manager, Opérateur, Comptable', max_length=100, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Rôle personnalisé',
                'verbose_name_plural': 'Rôles personnalisés',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: view_orders, manage_services, view_stats', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Nom lisible de la permission', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('orders', 'Gestion des commandes'), ('services', 'Gestion des services'), ('tariffs', 'Gestion des tarifs'), ('stats', 'Statistiques'), ('staff', 'Gestion du personnel'), ('settings', 'Paramètres'), ('customers', 'Gestion clients')], max_length=50, verbose_name='Module')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['code'], name='core_permis_code_4d467b_idx'), models.Index(fields=['module', 'is_active'], name='core_permis_module_226f6a_idx')],
            },
        ),
    ]
