# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='providers.provider', verbose_name='Prestataire'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='provider',
            field=models.ForeignKey(help_text='Le prestataire qui a créé ce rôle', on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='providers.provider', verbose_name='Prestataire'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('provider', 'name')},
        ),
    ]
