# Generated by Django 5.2.7 on 2025-10-16 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, help_text='Format: +225XXXXXXXXXX', max_length=20, verbose_name='Numéro de téléphone')),
                ('code_hash', models.CharField(help_text='Code haché pour sécurité', max_length=255, verbose_name='Hash du code OTP')),
                ('purpose', models.CharField(choices=[('signup', 'Inscription'), ('reset_password', 'Réinitialisation mot de passe'), ('phone_verification', 'Vérification téléphone'), ('login_2fa', 'Double authentification')], db_index=True, max_length=20, verbose_name='Objectif')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Nombre de tentatives de vérification', verbose_name='Tentatives')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expire le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de la requête', null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur/App de la requête', verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_verified'], name='core_otpcod_phone_498bf7_idx'), models.Index(fields=['expires_at', 'is_verified'], name='core_otpcod_expires_a01e53_idx'), models.Index(fields=['created_at'], name='core_otpcod_created_2e8d38_idx')],
            },
        ),
    ]
