# Generated by Django 5.2.7 on 2025-11-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_autheventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
