# Generated by Django 5.2.7 on 2026-01-23 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_provider_settings'),
        ('providers', '0004_alter_providerstaff_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='closed_reason',
            field=models.CharField(blank=True, help_text='Ex: Vacances, Panne machine, Trop de travail', max_length=200, verbose_name='Raison de fermeture'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='is_open',
            field=models.BooleanField(default=False, help_text="Si False, le pressing n'apparaît pas dans l'app client", verbose_name='Pressing ouvert'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Indique si le prestataire a terminé la configuration initiale', verbose_name='Onboarding terminé'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onboarding terminé le'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='onboarding_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onboarding commencé le'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non commencé'), (1, 'Identité du pressing'), (2, 'Services et tarifs'), (3, 'Informations de paiement'), (4, 'Terminé')], default=0, help_text='Étape actuelle du parcours de configuration', verbose_name="Étape d'onboarding"),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='storefront_photo',
            field=models.ImageField(blank=True, help_text="Photo de l'établissement visible par les clients", null=True, upload_to='providers/storefronts/%Y/%m/', verbose_name='Photo de la devanture'),
        ),
        migrations.CreateModel(
            name='ProviderPayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('phone_number', models.CharField(help_text='Numéro associé au compte Mobile Money', max_length=15, verbose_name='Numéro de téléphone')),
                ('account_name', models.CharField(help_text='Nom affiché sur le compte Mobile Money', max_length=200, verbose_name='Nom du titulaire')),
                ('is_primary', models.BooleanField(default=False, help_text='Compte utilisé par défaut pour les retraits', verbose_name='Compte principal')),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='Statut de vérification')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'ordering': ['-is_primary', '-created'],
                'indexes': [models.Index(fields=['provider', 'is_primary'], name='core_provid_provide_627b68_idx'), models.Index(fields=['operator', 'phone_number'], name='core_provid_operato_59df07_idx'), models.Index(fields=['status'], name='core_provid_status_917669_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'operator', 'phone_number'), name='unique_payout_account_per_provider')],
            },
        ),
    ]
