# Generated by Django 5.2.7 on 2026-01-23 19:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_onboarding_and_payout_accounts'),
        ('orders', '0002_order_agency_order_assigned_staff_and_more'),
        ('providers', '0005_add_ville_to_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Pourcentage prélevé sur chaque commande livrée', max_digits=5, verbose_name='Commission plateforme (%)')),
                ('moneroo_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Frais fixes par transaction payout (~$0.01)', max_digits=10, verbose_name='Frais Moneroo fixes (FCFA)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Commandes en dessous de ce montant sont bloquées', max_digits=10, verbose_name='Montant minimum commande (FCFA)')),
                ('min_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Montant minimum pour déclencher un payout', max_digits=10, verbose_name='Montant minimum retrait (FCFA)')),
                ('payout_delay_hours', models.PositiveIntegerField(default=2, help_text="Temps d'attente après validation OTP avant virement automatique", verbose_name='Délai avant payout (heures)')),
                ('delivery_otp_validity_minutes', models.PositiveIntegerField(default=60, help_text='Durée de validité du code OTP de livraison', verbose_name='Validité OTP livraison (minutes)')),
                ('moneroo_api_key', models.CharField(blank=True, help_text="Clé secrète pour l'API Moneroo", max_length=255, verbose_name='Clé API Moneroo')),
                ('moneroo_webhook_secret', models.CharField(blank=True, help_text='Secret pour valider les webhooks Moneroo', max_length=255, verbose_name='Secret Webhook Moneroo')),
                ('moneroo_sandbox_mode', models.BooleanField(default=True, help_text="Utiliser l'environnement de test Moneroo", verbose_name='Mode Sandbox Moneroo')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Configuration supplémentaire en JSON', verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration plateforme',
                'verbose_name_plural': 'Configuration plateforme',
            },
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant disponible pour retrait', max_digits=12, verbose_name='Solde disponible (FCFA)')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant en attente de virement (< délai payout)', max_digits=12, verbose_name='Solde en attente (FCFA)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulé depuis le début', max_digits=12, verbose_name='Total gagné (FCFA)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des retraits effectués', max_digits=12, verbose_name='Total retiré (FCFA)')),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des commissions prélevées par la plateforme', max_digits=12, verbose_name='Total commissions payées (FCFA)')),
                ('orders_completed', models.PositiveIntegerField(default=0, help_text='Nombre total de commandes livrées', verbose_name='Commandes complétées')),
                ('last_payout_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier retrait le')),
                ('is_active', models.BooleanField(default=True, help_text='Si False, les retraits sont bloqués', verbose_name='Wallet actif')),
                ('suspended_reason', models.CharField(blank=True, max_length=255, verbose_name='Raison de suspension')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Portefeuille prestataire',
                'verbose_name_plural': 'Portefeuilles prestataires',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé (FCFA)')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais de transfert (FCFA)')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Montant réellement reçu par le prestataire', max_digits=12, verbose_name='Montant net (FCFA)')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence interne')),
                ('moneroo_payout_id', models.CharField(blank=True, max_length=200, verbose_name='ID Payout Moneroo')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="Date/heure d'exécution prévue", null=True, verbose_name='Programmé pour')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('is_automatic', models.BooleanField(default=True, help_text='True si déclenché automatiquement après OTP', verbose_name='Payout automatique')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Réponse Moneroo, détails de la commande, etc.', verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('order', models.ForeignKey(blank=True, help_text='Si payout automatique après livraison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_requests', to='orders.order', verbose_name='Commande liée')),
                ('payout_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='core.providerpayoutaccount', verbose_name='Compte de destination')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.providerwallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('order_payment', 'Paiement commande'), ('commission', 'Commission plateforme'), ('payout', 'Retrait Mobile Money'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement manuel'), ('bonus', 'Bonus/Prime')], max_length=20, verbose_name='Type de transaction')),
                ('direction', models.CharField(choices=[('credit', 'Crédit (+)'), ('debit', 'Débit (-)')], max_length=10, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après transaction')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True, verbose_name='Référence')),
                ('external_reference', models.CharField(blank=True, help_text='ID Moneroo ou autre référence externe', max_length=200, verbose_name='Référence externe')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='completed', max_length=20, verbose_name='Statut')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires (frais, commission, etc.)', verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='Commande liée')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.providerwallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='providerwallet',
            index=models.Index(fields=['provider'], name='core_provid_provide_38f628_idx'),
        ),
        migrations.AddIndex(
            model_name='providerwallet',
            index=models.Index(fields=['balance'], name='core_provid_balance_c95612_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['wallet', 'status'], name='core_payout_wallet__421909_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['reference'], name='core_payout_referen_eab817_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['moneroo_payout_id'], name='core_payout_moneroo_6c0fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['scheduled_at', 'status'], name='core_payout_schedul_643775_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['order'], name='core_payout_order_i_79eb29_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='core_wallet_wallet__75d1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created'], name='core_wallet_wallet__8ed01d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='core_wallet_referen_2249a2_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['order'], name='core_wallet_order_i_7c5887_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='core_wallet_status_864d6e_idx'),
        ),
    ]
