# Generated by Django 5.2.7 on 2026-01-24 02:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wallet_and_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='moneroo_fee_fixed',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='collect_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text="Frais CinetPay à l'encaissement (~3% Orange, ~1.8% MTN)", max_digits=5, verbose_name='Frais Collect (%)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gateway_api_key',
            field=models.CharField(blank=True, help_text="Clé secrète pour l'API de paiement", max_length=255, verbose_name='Clé API'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gateway_sandbox_mode',
            field=models.BooleanField(default=True, help_text="Utiliser l'environnement de test", verbose_name='Mode Sandbox/Test'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gateway_site_id',
            field=models.CharField(blank=True, help_text='Identifiant du site pour CinetPay', max_length=100, verbose_name='Site ID (CinetPay)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gateway_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret pour valider les webhooks', max_length=255, verbose_name='Secret Webhook'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payment_gateway',
            field=models.CharField(choices=[('cinetpay', 'CinetPay'), ('moneroo', 'Moneroo'), ('simulation', 'Simulation locale')], default='cinetpay', help_text='Service utilisé pour les paiements', max_length=50, verbose_name='Passerelle de paiement'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Frais CinetPay au virement (~1.5% Orange, ~1.3% MTN)', max_digits=5, verbose_name='Frais Payout (%)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pourcentage prélevé sur chaque commande livrée (recommandé: 3%)', max_digits=5, verbose_name='Commission plateforme (%)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='delivery_otp_validity_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Durée de validité du code OTP de livraison', verbose_name='Validité OTP livraison (minutes)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='moneroo_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='[Legacy] Clé API Moneroo'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='moneroo_sandbox_mode',
            field=models.BooleanField(default=True, verbose_name='[Legacy] Mode Sandbox Moneroo'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='moneroo_webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='[Legacy] Secret Webhook Moneroo'),
        ),
    ]
