# Generated by Django 5.2.7 on 2026-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_payment_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='login_alerts',
            field=models.BooleanField(default=True, help_text='Notification en cas de nouvelle connexion', verbose_name='Alertes de connexion'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='Max commandes par jour'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='notify_new_orders',
            field=models.BooleanField(default=True, help_text='Notification à chaque nouvelle commande', verbose_name='Nouvelles commandes'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='notify_order_updates',
            field=models.BooleanField(default=True, help_text='Annulations, modifications de commandes', verbose_name='Mises à jour commandes'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='notify_payments',
            field=models.BooleanField(default=True, help_text='Notification quand un paiement est confirmé', verbose_name='Paiements reçus'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='notify_reminders',
            field=models.BooleanField(default=True, help_text='Rappels pour commandes en attente', verbose_name='Rappels'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='pause_mode',
            field=models.BooleanField(default=False, help_text="Mettre temporairement le pressing en pause (n'accepte plus de commandes)", verbose_name='Mode pause'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='pause_reason',
            field=models.CharField(blank=True, help_text='Ex: Vacances, Maintenance, etc.', max_length=200, verbose_name='Raison de la pause'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text="Notifications sur l'appareil (navigateur/mobile)", verbose_name='Notifications push'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='two_factor_auth',
            field=models.BooleanField(default=False, help_text='Double vérification lors de la connexion', verbose_name='Authentification à deux facteurs'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text="Liste des jours: ['monday', 'tuesday', ...]", verbose_name='Jours de travail'),
        ),
        migrations.AlterField(
            model_name='providersettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Si vide, utilise l'email du compte", max_length=254, verbose_name='Email de notification'),
        ),
        migrations.AlterField(
            model_name='providersettings',
            name='notification_phone',
            field=models.CharField(blank=True, help_text='Si vide, utilise le téléphone du compte', max_length=15, verbose_name='Téléphone de notification'),
        ),
        migrations.AlterField(
            model_name='providersettings',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='SMS facturés, à activer avec précaution', verbose_name='Notifications par SMS'),
        ),
    ]
