# Generated by Django 5.2.7 on 2026-01-25 22:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_providersettings_login_alerts_and_more'),
        ('orders', '0003_wallet_and_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant utilisable pour payer des commandes', max_digits=12, verbose_name='Solde disponible (FCFA)')),
                ('total_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des crédits reçus (remboursements, trop-perçus)', max_digits=12, verbose_name='Total crédité (FCFA)')),
                ('total_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des crédits utilisés pour payer des commandes', max_digits=12, verbose_name='Total utilisé (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Wallet actif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Portefeuille client',
                'verbose_name_plural': 'Portefeuilles clients',
            },
        ),
        migrations.CreateModel(
            name='ClientWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('refund', 'Remboursement commande'), ('overpayment', 'Trop-perçu (livreur a constaté moins)'), ('payment', 'Paiement avec crédit'), ('adjustment', 'Ajustement manuel'), ('promo', 'Crédit promotionnel')], max_length=20, verbose_name='Type de transaction')),
                ('direction', models.CharField(choices=[('credit', 'Crédit (+)'), ('debit', 'Débit (-)')], max_length=10, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après transaction')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='completed', max_length=20, verbose_name='Statut')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_wallet_transactions', to='orders.order', verbose_name='Commande liée')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.clientwallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction wallet client',
                'verbose_name_plural': 'Transactions wallet client',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='clientwallet',
            index=models.Index(fields=['user'], name='core_client_user_id_c23801_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwallet',
            index=models.Index(fields=['balance'], name='core_client_balance_9e154f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwallettransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='core_client_wallet__b20064_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwallettransaction',
            index=models.Index(fields=['wallet', 'created'], name='core_client_wallet__02136f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwallettransaction',
            index=models.Index(fields=['reference'], name='core_client_referen_497989_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwallettransaction',
            index=models.Index(fields=['order'], name='core_client_order_i_06c8bd_idx'),
        ),
    ]
