# Generated by Django 5.2.7 on 2025-10-10 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pressing', 'Pressing'), ('fanico', 'Fanico')], max_length=20, verbose_name='Type de prestataire')),
                ('nom_commercial', models.CharField(help_text="Nom de l'établissement ou du prestataire", max_length=200, verbose_name='Nom commercial')),
                ('photo_local', models.ImageField(blank=True, help_text="Photo de l'établissement (facultatif pour fanico)", null=True, upload_to='providers/locaux/%Y/%m/', verbose_name='Photo du local')),
                ('zone_couverture', models.TextField(help_text='Quartiers ou communes desservis', verbose_name='Zone de couverture')),
                ('rayon_km', models.DecimalField(decimal_places=2, default=5.0, help_text='Distance maximale de déplacement', max_digits=5, verbose_name='Rayon de couverture (km)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('statut_kyc', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut KYC')),
                ('document_identite', models.FileField(blank=True, help_text='CNI, Passeport, etc.', null=True, upload_to='providers/kyc/%Y/%m/', verbose_name="Document d'identité")),
                ('is_active', models.BooleanField(default=True, help_text='Le prestataire peut recevoir des commandes', verbose_name='Actif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'ordering': ['-created'],
            },
        ),
    ]
