# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['type', 'is_active'], name='providers_p_type_1a8423_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['latitude', 'longitude'], name='providers_p_latitud_07070d_idx'),
        ),
    ]
