# Generated by Django 5.2.7 on 2025-11-16 03:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_otpcode'),
        ('providers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('pressing', 'Pressing'), ('laverie', 'Laverie'), ('blanchisserie', 'Blanchisserie'), ('fanico', 'Fanico'), ('pressing_chaussures', 'Pressing de chaussures'), ('nettoyage', 'Nettoyage'), ('autre', 'Autre')], max_length=20, verbose_name='Type de prestataire'),
        ),
        migrations.CreateModel(
            name='ProviderAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('code', models.CharField(blank=True, help_text='Identifiant court (optionnel)', max_length=32, verbose_name='Code agence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=120, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=120, verbose_name='Quartier / Commune')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Localisation')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Personne de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone de contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name="Horaires d'ouverture")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('is_default', models.BooleanField(default=False, help_text='Agence affichée par défaut pour la gestion', verbose_name='Agence principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_role', models.CharField(choices=[('owner', 'Propriétaire'), ('manager', 'Manager'), ('operator', 'Opérateur'), ('delivery', 'Livreur'), ('custom', 'Rôle personnalisé')], default='operator', max_length=20, verbose_name='Rôle système')),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('revoked', 'Révoqué')], default='invited', max_length=20, verbose_name='Statut')),
                ('invited_email', models.EmailField(blank=True, max_length=254, verbose_name="Email d'invitation")),
                ('invited_phone', models.CharField(blank=True, max_length=32, verbose_name="Téléphone d'invitation")),
                ('invite_token', models.CharField(blank=True, max_length=128, verbose_name="Jeton d'invitation")),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Invité le')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activé le')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='providers.provideragency', verbose_name='Agence')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='providers.provider', verbose_name='Prestataire')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.role', verbose_name='Rôle personnalisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre du staff',
                'verbose_name_plural': 'Staff du prestataire',
            },
        ),
        migrations.AddIndex(
            model_name='provideragency',
            index=models.Index(fields=['provider', 'is_active'], name='providers_p_provide_df7608_idx'),
        ),
        migrations.AddIndex(
            model_name='provideragency',
            index=models.Index(fields=['ville', 'quartier'], name='providers_p_ville_11f11c_idx'),
        ),
        migrations.AddConstraint(
            model_name='provideragency',
            constraint=models.UniqueConstraint(condition=models.Q(('code__exact', ''), _negated=True), fields=('provider', 'code'), name='unique_agency_code_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='provideragency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider',), name='unique_default_agency_per_provider'),
        ),
        migrations.AddIndex(
            model_name='providerstaff',
            index=models.Index(fields=['provider', 'status'], name='providers_p_provide_405f74_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstaff',
            index=models.Index(fields=['agency'], name='providers_p_agency__b0d52f_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstaff',
            index=models.Index(fields=['system_role'], name='providers_p_system__4ba0fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerstaff',
            unique_together={('provider', 'user')},
        ),
    ]
