# Generated by Django 5.2.7 on 2025-11-16 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_otpcode'),
        ('providers', '0003_alter_provider_type_provideragency_providerstaff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerstaff',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='providerstaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='providerstaff',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('provider', 'user'), name='unique_staff_user_per_provider'),
        ),
    ]
