# Generated by Django 5.2.7 on 2026-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerstaff_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ville',
            field=models.CharField(blank=True, help_text='Ville du prestataire', max_length=120, verbose_name='Ville'),
        ),
    ]
