# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Généré automatiquement (ex: ORD-2024-0001)', max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('adresse_collecte', models.TextField(verbose_name='Adresse de collecte')),
                ('latitude_collecte', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude collecte')),
                ('longitude_collecte', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude collecte')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('latitude_livraison', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude livraison')),
                ('longitude_livraison', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude livraison')),
                ('creneau_collecte', models.DateTimeField(help_text='Date et heure souhaitées pour la collecte', verbose_name='Créneau de collecte')),
                ('creneau_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Créneau de livraison estimé')),
                ('date_collecte', models.DateTimeField(blank=True, null=True, verbose_name='Date de collecte réelle')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('collected', 'Collectée'), ('in_progress', 'En cours'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('total_estime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total estimé (FCFA)')),
                ('total_final', models.DecimalField(blank=True, decimal_places=2, help_text='Montant réel après traitement', max_digits=10, null=True, verbose_name='Total final (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de livraison (FCFA)')),
                ('notes_client', models.TextField(blank=True, help_text='Instructions particulières', verbose_name='Notes du client')),
                ('notes_provider', models.TextField(blank=True, help_text='Observations lors du traitement', verbose_name='Notes du prestataire')),
                ('preuve_livraison_url', models.URLField(blank=True, help_text='Signature ou photo de livraison', verbose_name='URL preuve de livraison')),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='orders/signatures/%Y/%m/', verbose_name='Signature client')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['client', 'statut'], name='orders_orde_client__821a47_idx'), models.Index(fields=['provider', 'statut'], name='orders_orde_provide_9e5ebd_idx'), models.Index(fields=['numero'], name='orders_orde_numero_50678f_idx')],
            },
        ),
    ]
