# Generated by Django 5.2.7 on 2025-10-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.provider', verbose_name='Prestataire'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'statut'], name='orders_orde_client__821a47_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', 'statut'], name='orders_orde_provide_9e5ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['numero'], name='orders_orde_numero_50678f_idx'),
        ),
    ]
