# Generated by Django 5.2.7 on 2025-11-19 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('providers', '0004_alter_providerstaff_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='providers.provideragency', verbose_name='Agence assignée'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='providers.providerstaff', verbose_name='Staff assigné'),
        ),
        migrations.AddField(
            model_name='order',
            name='statut_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de statut'),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('creation', 'Création'), ('status_change', 'Changement de statut'), ('assignment', 'Affectation'), ('note', 'Note')], default='status_change', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('collected', 'Collectée'), ('in_progress', 'En cours'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=20, null=True, verbose_name='Statut précédent')),
                ('new_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('collected', 'Collectée'), ('in_progress', 'En cours'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=20, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='Commande')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Journal de statut',
                'verbose_name_plural': 'Journaux de statut',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['order', 'event'], name='orders_orde_order_i_9797ac_idx'), models.Index(fields=['new_status'], name='orders_orde_new_sta_576226_idx')],
            },
        ),
    ]
