# Generated by Django 5.2.7 on 2026-01-23 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_agency_order_assigned_staff_and_more'),
        ('providers', '0005_add_ville_to_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, verbose_name="Notes d'annulation"),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Code raison: too_busy, machine_down, client_request, etc.', max_length=50, verbose_name="Raison d'annulation"),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulé le'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant commission (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Commission appliquée (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, help_text='Code à 6 chiffres pour valider la livraison', max_length=6, verbose_name='Code OTP livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP généré le'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP validé le'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='OTP validé par'),
        ),
        migrations.AddField(
            model_name='order',
            name='moneroo_payment_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Paiement Moneroo'),
        ),
        migrations.AddField(
            model_name='order',
            name='moneroo_payout_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Payout Moneroo'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payé le'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='orange_money, mtn_momo, wave, etc.', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('escrow', 'En séquestre'), ('released', 'Libéré'), ('refunded', 'Remboursé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut paiement client'),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payout envoyé le'),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais payout Moneroo (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure du virement automatique (après délai)', null=True, verbose_name='Payout programmé pour'),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('not_applicable', 'Non applicable'), ('pending', 'En attente'), ('scheduled', 'Programmé'), ('processing', 'En cours'), ('completed', 'Envoyé'), ('failed', 'Échoué')], default='not_applicable', max_length=20, verbose_name='Statut payout prestataire'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total - Commission - Frais Moneroo', max_digits=10, verbose_name='Montant net prestataire (FCFA)'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payout_status'], name='orders_orde_payout__9e12d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payout_scheduled_at', 'payout_status'], name='orders_orde_payout__5fcb06_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_otp_validated_at'], name='orders_orde_deliver_2d0473_idx'),
        ),
    ]
