# Generated by Django 5.2.7 on 2026-01-25 22:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_wallet_and_payout'),
        ('providers', '0005_add_ville_to_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Différence positive = client doit payer plus, négative = crédit client', max_digits=10, verbose_name="Montant d'ajustement (FCFA)"),
        ),
        migrations.AddField(
            model_name='order',
            name='adjustment_deadline',
            field=models.DateTimeField(blank=True, help_text='Passé ce délai, le livreur ne prend que ce qui correspond au montant payé', null=True, verbose_name='Date limite pour complément'),
        ),
        migrations.AddField(
            model_name='order',
            name='adjustment_moneroo_payment_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Paiement ajustement Moneroo'),
        ),
        migrations.AddField(
            model_name='order',
            name='adjustment_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ajustement payé le'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_accepted_reduction',
            field=models.BooleanField(default=False, help_text='True si le client a choisi de retirer du linge plutôt que compléter', verbose_name='Client a accepté la réduction'),
        ),
        migrations.AddField(
            model_name='order',
            name='counting_mode',
            field=models.CharField(choices=[('client', 'Client compte lui-même'), ('collector', 'Livreur compte à la collecte')], default='client', help_text='Qui compte les articles : client ou livreur à la collecte', max_length=20, verbose_name='Mode de comptage'),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_issued',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Crédit ajouté au portefeuille client si trop-perçu', max_digits=10, verbose_name='Crédit émis (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de pièces déclaré par le client', null=True, verbose_name='Nombre de pièces estimé'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids déclaré par le client', max_digits=8, null=True, verbose_name='Poids estimé (kg)'),
        ),
        migrations.AddField(
            model_name='order',
            name='initial_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Premier paiement du client basé sur son estimation', max_digits=10, verbose_name='Montant initial payé (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='photos_submitted',
            field=models.BooleanField(default=False, help_text='Le client a soumis des photos des articles', verbose_name='Photos soumises'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quantité vérifiée le'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to='providers.providerstaff', verbose_name='Quantité vérifiée par'),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de pièces réel constaté par le livreur', null=True, verbose_name='Nombre de pièces vérifié'),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids réel constaté par le livreur', max_digits=8, null=True, verbose_name='Poids vérifié (kg)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid_pending_verification', 'Payé - Vérification en cours'), ('paid', 'Payé'), ('adjustment_required', 'Complément requis'), ('escrow', 'En séquestre'), ('released', 'Libéré'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé'), ('failed', 'Échoué')], default='pending', max_length=30, verbose_name='Statut paiement client'),
        ),
    ]
