# Generated by Django 5.2.7 on 2026-01-25 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_quantity_verification_and_client_wallet'),
        ('providers', '0005_add_ville_to_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claim_admin_notes',
            field=models.TextField(blank=True, help_text='Notes internes de Pressow pour le traitement', verbose_name='Notes admin sur la réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_deadline',
            field=models.DateTimeField(blank=True, help_text='Le client a 30 minutes après livraison pour faire une réclamation', null=True, verbose_name='Date limite de réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_details',
            field=models.TextField(blank=True, help_text='Description détaillée du problème par le client', verbose_name='Détails de la réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_photos',
            field=models.JSONField(blank=True, default=list, help_text='URLs des photos téléchargées par le client', verbose_name='Photos de réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Vêtements endommagés'), ('lost', 'Vêtements perdus'), ('stained', 'Taches non enlevées'), ('wrong_items', 'Mauvais articles reçus'), ('incomplete', 'Commande incomplète'), ('quality', 'Qualité insuffisante'), ('other', 'Autre')], max_length=30, verbose_name='Raison de la réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Réclamation résolue le'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_status',
            field=models.CharField(choices=[('none', 'Aucune réclamation'), ('pending', 'En attente de traitement'), ('under_review', "En cours d'examen"), ('resolved', 'Résolue'), ('rejected', 'Rejetée')], default='none', max_length=20, verbose_name='Statut de réclamation'),
        ),
        migrations.AddField(
            model_name='order',
            name='claim_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Réclamation soumise le'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['claim_deadline', 'claim_status'], name='orders_orde_claim_d_5d320e_idx'),
        ),
    ]
