# Generated by Django 5.2.7 on 2025-10-10 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, help_text='Nombre de pièces ou poids en kg selon le service', max_digits=8, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ligne (FCFA)')),
                ('photo', models.ImageField(blank=True, help_text='Photo facultative du vêtement', null=True, upload_to='order_items/photos/%Y/%m/', verbose_name="Photo de l'article")),
                ('notes', models.TextField(blank=True, help_text='État, taches particulières, etc.', verbose_name='Notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='services.articletype', verbose_name="Type d'article")),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='services.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'ordering': ['order', 'created'],
            },
        ),
    ]
