# Generated by Django 5.2.7 on 2025-10-15 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('providers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('note_qualite', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note qualité')),
                ('note_delai', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note respect des délais')),
                ('note_service', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note service client')),
                ('is_approved', models.BooleanField(default=True, help_text="L'avis est visible publiquement", verbose_name='Approuvé')),
                ('is_flagged', models.BooleanField(default=False, help_text="L'avis a été signalé pour modération", verbose_name='Signalé')),
                ('reponse_provider', models.TextField(blank=True, verbose_name='Réponse du prestataire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('order', models.OneToOneField(help_text='Un avis par commande', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Commande')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['provider', 'is_approved'], name='reviews_rev_provide_c4b801_idx'), models.Index(fields=['client'], name='reviews_rev_client__578445_idx')],
            },
        ),
    ]
