# Generated by Django 5.2.7 on 2025-10-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('providers', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(help_text='Un avis par commande', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.provider', verbose_name='Prestataire'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', 'is_approved'], name='reviews_rev_provide_c4b801_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client'], name='reviews_rev_client__578445_idx'),
        ),
    ]
