# Generated by Django 5.2.7 on 2025-10-10 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Référence unique du paiement', max_length=100, unique=True, verbose_name='Référence de paiement')),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('wave', 'Wave')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('numero_payeur', models.CharField(max_length=15, verbose_name='Numéro du payeur')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, help_text="ID fourni par l'opérateur Mobile Money", max_length=200, verbose_name='ID de transaction externe')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires de la transaction', verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('date_initiation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'initiation")),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Est un remboursement')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Commande')),
                ('refund_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.payment', verbose_name='Remboursement de')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['order', 'statut'], name='payments_pa_order_i_3434ad_idx'), models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
