# Serializers Presso API
# Tous les serializers sont organisés par module

from .auth import (
    ClientRegisterSerializer,
    ProviderRegisterSerializer,
    LoginSerializer,
    OTPRequestSerializer,
    OTPVerifySerializer,
    PasswordResetRequestSerializer,
    PasswordResetVerifySerializer,
    PasswordResetFinalizeSerializer,
    UserProfileSerializer,
    PasswordChangeSerializer,
)
from .providers import (
    ProviderAgencySerializer,
    ProviderAgencyWriteSerializer,
    ProviderStaffSerializer,
    ProviderStaffInviteSerializer,
    ProviderStaffUpdateSerializer,
    ProviderStaffActivateSerializer,
    ProviderSettingsSerializer,
    ProviderSettingsUpdateSerializer,
    ProviderServiceSerializer,
    ProviderServiceWriteSerializer,
    ArticleTypeSerializer,
    ArticleTypeWriteSerializer,
    MatiereSerializer,
    MatiereWriteSerializer,
    TariffSerializer,
    TariffWriteSerializer,
)
from .orders import (
    OrderCreateSerializer,
    OrderSerializer,
    ProviderOrderStatusSerializer,
    ProviderOrderAssignSerializer,
)
from .onboarding import (
    OnboardingStatusSerializer,
    OnboardingIdentitySerializer,
    OnboardingServicesSerializer,
    OnboardingServiceItemSerializer,
    OnboardingPayoutAccountSerializer,
    ProviderPayoutAccountReadSerializer,
    OnboardingCompleteResponseSerializer,
    ProviderOpenStatusSerializer,
)

__all__ = [
    'ClientRegisterSerializer',
    'ProviderRegisterSerializer',
    'LoginSerializer',
    'OTPRequestSerializer',
    'OTPVerifySerializer',
    'PasswordResetRequestSerializer',
    'PasswordResetVerifySerializer',
    'PasswordResetFinalizeSerializer',
    'UserProfileSerializer',
    'PasswordChangeSerializer',
    'ProviderAgencySerializer',
    'ProviderAgencyWriteSerializer',
    'ProviderStaffSerializer',
    'ProviderStaffInviteSerializer',
    'ProviderStaffUpdateSerializer',
    'ProviderStaffActivateSerializer',
    'ProviderSettingsSerializer',
    'ProviderSettingsUpdateSerializer',
    'ProviderServiceSerializer',
    'ProviderServiceWriteSerializer',
    'ArticleTypeSerializer',
    'ArticleTypeWriteSerializer',
    'MatiereSerializer',
    'MatiereWriteSerializer',
    'TariffSerializer',
    'TariffWriteSerializer',
    'OrderCreateSerializer',
    'OrderSerializer',
    'ProviderOrderStatusSerializer',
    'ProviderOrderAssignSerializer',
    # Onboarding
    'OnboardingStatusSerializer',
    'OnboardingIdentitySerializer',
    'OnboardingServicesSerializer',
    'OnboardingServiceItemSerializer',
    'OnboardingPayoutAccountSerializer',
    'ProviderPayoutAccountReadSerializer',
    'OnboardingCompleteResponseSerializer',
    'ProviderOpenStatusSerializer',
]

